# Generated by Django 4.0 on 2021-12-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='artigo',
            field=models.IntegerField(verbose_name='Artigo'),
        ),
    ]
